spring.application.name=web5

# 소스 코드(HTML, JS, CSS 등 정적 리소스)가 바꼈을 때, 브라우저를 자동으로 새로고침 해주는 기능
spring.devtools.livereload.enabled=true

# cache=false로 하면 매 요청마다 템플릿 파일을 다시 읽어들임
# 템플릿 수정 후 서버 재시작 없이 바로 적용됨
# 단점: 성능은 조금 떨어지지만, 개발 중에는 상관없음
spring.freemarker.cache=false


## 경로 ######################################################
server.port=9995
server.servlet.context-path=/


## 로그 ######################################################
# 전체를 대상으로 로깅 레벨 지정(Logback)
# error > warn > info > debug > trace
logging.level.root=info
# 특정 패키지를 대상으로 로깅 레벨 지정
logging.level.net.datasa.web5=debug


## 세션 ######################################################
# 세션 만료 시간 설정 - 단위 : s (seconds), m (minutes), h (hours), d (days)
server.servlet.session.timeout=60m


## MySQL ####################################################
# 프로젝트의 바로 하위 디렉토리(build.gradle, .gitignore 파일들과 동일한 위치일 것)에 .env 파일 생성
# 해당 파일에 설정 정보들 입력
# .gitignore 에 .env 작성

# 인텔리제이 플러그인(EnvFile) 도움 없이, 스프링 부트가 스스로 .env 파일을 직접 읽어서 연동하게 만드는 설정
spring.config.import=optional:file:.env[.properties]

# 데이터베이스 연결 주소 (localhost 및 포트, 데이터베이스명은 본인 환경에 맞게 수정하세요)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


## JPA ######################################################
# JPA 설정
# JPA가 실행하는 SQL을 콘솔에 출력하도록 하는 옵션
spring.jpa.show-sql=true
# DDL(스키마) 자동 생성 전략 - JPA가 DB 스키마를 자동으로 생성·관리할 것인지를 결정하기 위해
#   none        아무 작업도 하지 않음
#   validate    DB와 엔티티가 같은지 확인만 하고, 다르면 에러 발생
#   update      있는 테이블은 유지하되, 변화된 스키마를 자동 업데이트
#   create      서버 실행 시 스키마를 새로 생성(기존 테이블 삭제)
#   create-drop create와 같지만 종료 시 테이블 삭제
spring.jpa.hibernate.ddl-auto=validate
# 데이터베이스마다 SQL 문법이 조금씩 다르기 때문에, MySQL 버전을 사용하겠다는 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# SQL을 콘솔에 포맷팅 해서 출력
spring.jpa.properties.hibernate.format_sql=true
# SQL 바인딩 파라미터 로깅 (Spring Boot 버전에 따라 설정이 다를 수 있어 가장 확실한 2가지 모두 추가)
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.results.mapping=trace


## FILE #####################################################
# 업로드 용량 제한: default 1M(1048576)
# 파일 1개당 최대 크기
spring.servlet.multipart.maxFileSize=10MB
# 요청 전체 크기(여러 파일 + 폼 데이터 합)
spring.servlet.multipart.maxRequestSize=100MB
# 업로드 처리 도중 잠깐 맡겨두는 폴더
spring.servlet.multipart.location=c:/tempUpload


## 사용자 정의 ################################################
# 사용자 정의 속성값 설정
board.pageSize=10
board.linkSize=2
# 최종적으로 파일을 저장할 위치(영구 저장소)
board.uploadPath=c:/upload